### ISSUE TITLE
Constant bikeshedding

### ISSUE THREAD

**Issue by paholg** [paholg/dimensioned#16]
Right now, a constant is defined for each unit we create. They tend to have names like `m` for 1 meter.

There's a couple things I don't like about this.

First, it goes against Rust's naming convention that constants should be uppercase -- but I think I like making these constants uppercase even less.

Second, it requires us to choose a "blessed" primitive when creating a unit system. Right now it's been `f64`, but what if you want `f32` or something else? Well then you have to make your own anyway.

Recent changes to dimensioned mean that instead of `Dim<Meter, f64>` you write `Meter<f64>`, which means it's much cleaner to construct units without the consts.

The old way:

``` rust
let x: Dim<Meter, f64> = Dim::new(3.4);
```

The new way:

``` rust
let x = Meter::new(3.4);
```

This increase in constructor ergonomics makes want to get rid of pre-defining constants, but I figured I'd post this issue first in case anyone else has thoughts on the matter.

**Comment by paholg** [comment]
Thinking about this more, we're definitely going to want to include a lot of constants, for things like

```rust
const ft: Meter<f64> = Meter::new(0.305);
```

but maybe that would be better as a generic function?

**Comment by droundy** [comment]
It looks like you've hit on a reason for defining constants: it actually
enables you to abstract away the base units, in a sense, since there is no
difference between m and cm.  But maybe the constants should go in a
separate optional module?

**Comment by iliekturtles** [comment]
I think having the constants/conversions factors in the library is what will make it valuable. It also gives a single, reviewed, source for all constants, instead of every user having to enter any needed conversions on their own.

I've been doing some experiments (most current at https://github.com/iliekturtles/uom/tree/dev-8) and ended up with the base struct being `Length` and not `Meter` or `Foot`. Conversion factors are used internally and also exposed as enum variants: `length::Units::meter`, `length::Units::foot`, ...

**Comment by paholg** [comment]
Constants are in for sure, so I've renamed this as there are some open issues.

Say, for example, that we have the module `si` with the `SI` system defined in it.

## Structure

Do we also have `consts` in that module? On the plus side, that makes them quite nice to use, as you  can `use dim::si;` then things like `si::m` are both concise and clear. On the down side, if you wish to do a glob import from `si`, that could get ugly. We could also make an `si::prelude` module for glob imports of just the types....

## Type
What primitive should consts be? I think `f64` is a good default, but it'd be nice to have `f32` ones also. This could be done either with a `si::consts32` module, or with names like `si::m32`. I don't know what's best.

## Functions
In addition to consts, do we also define functions? We already have things like `Meter::new(3.0)`, but something like `3.0.m();` could be nice. It has the benefit over consts that it could be generic, and the same function could work for `f32` and `f64`.

**Comment by iliekturtles** [comment]
In my experiments (https://github.com/iliekturtles/uom/blob/dev-8/src/si/mod.rs#L32) I went with both f32 and f64 consts with the intention to add default features for both so that the undesired consts could be disabled.

**Comment by paholg** [comment]
That seems like a good idea. What I have now is, in each unit system, an `f32consts` module and an `f64consts` module, with a `pub use f64consts::*`. So users have access to both, but `f64` is a bit more convenient.

**Comment by paholg** [comment]
I think this is settled.
