### ISSUE TITLE
Imperial alternative to SI?

### ISSUE THREAD

**Issue by paholg** [paholg/dimensioned#19]
It would be nice to include an equivalent unit system to SI that uses imperial units.

I'm not sure what units it should use, though. For example, do we use feet for length? Inches? Miles? Furlongs?

Given that, it might make more sense that people would want to define their own with whatever units make the most sense.

I would still like to define at least one, to give a nice example of converting to and from SI, and for interoperability, so that even if someone makes their own unit system, the could define a conversion to ours to work with other crates.

For reference, SI has 7 base units: meter, kilogram, second, ampere, kelvin, candela, mole.

**Comment by paholg** [comment]
This seems a good place to start: https://en.wikipedia.org/wiki/Foot–pound–second_system

So we would use feet for length and second for time.

Pounds are a question -- use force pounds and slugs for mass, or pounds as mass and poundals for force?

It looks like it does E&M units similarly to cgs, so that's interesting.

**Comment by iliekturtles** [comment]
At least here in the US pound-mass and pound-force are much more common for casual usage. This gives an [incoherent](https://en.wikipedia.org/wiki/Foot%E2%80%93pound%E2%80%93second_system#Pound_as_force_unit) system. I take it that this isn't possible with the current system? If one needs to be chosen, pound-mass is generally the meaning when someone references "pounds."

For engineering use my experience has been that each piece of equipment has its own standard units based on it's history and development and coherent systems be damned!

**Comment by droundy** [comment]
Why not define poundforce and poundmass as two different units? PSI is a
very natural and common unit.  If I had to choose I'd want pounds force.
