### ISSUE TITLE
travis fails to build

### ISSUE THREAD

**Issue by droundy** [paholg/dimensioned#46]
The trouble is that `cargo fmt` is currently breaking the code.  See:

https://github.com/rust-lang-nursery/rustfmt/issues/2880

Presumably this is a newish bug in cargo, since the last commit on master passed, but for now it's making pull requests fail.

**Comment by paholg** [comment]
I remember running into this; I recall the fix being to use the nightly version of `rustfmt`, but maybe there was a regression.

**Comment by paholg** [comment]
Testing some more, this was fixed in 1.28.0. I had to reinstall 1.27.0 to reproduce it.
