### ISSUE TITLE
Use conventional letter case

### ISSUE THREAD

**Issue by adundovi** [paholg/dimensioned#76]
Instead of `si::M`, I would prefer to stick to the original letter case, i.e., `si::m`. I suppose it is not Rust-style, however, the correct letter case would avoid some clashes of derived and combined units. See the [following](https://usma.org/correct-si-metric-usage#locale-notification):

> Symbols are case-sensitive, so the meaning of an SI symbol can be changed if you substitute an uppercase letter for a lowercase letter. 
>    Correct: mm (for millimetre, which means 1/1000 of a metre)
>    Incorrect: MM or Mm (M is the symbol for the prefix mega-, which means one million; a megametre is a million metres)

**Comment by paholg** [comment]
I thought about this a lot when creating dimensioned, and settled on Rust style. I am unlikely to change it now unless one can come up with a very compelling case.

You are welcome to rename them in your code.
