### ISSUE TITLE
Support f256 via the qd github repo

### ISSUE THREAD

**Issue by MarkSwanson** [paholg/dimensioned#77]
Hello,

I'd like to investigate dimensioned, but I need f256 support for the quantum mechanics work I'd like to do.
Planck's constant is 6.62607015 × 10−34  so even f128 isn't good enough.

If you give me a few pointers I could take a stab at adding f256 support to dimensioned.

Thanks!

**Comment by paholg** [comment]
dimensioned is already generic with regards to value type, so it should work out of the box. You just won't be able to use the default constants, but you can make your own.

Imagine that dimensioned only supported `f32`, then you could write the following to use `f64`:

```rust
#[macro_use]
extern crate dimensioned;

use std::marker::PhantomData;

use dimensioned::{
    derived,
    si::{self, Kilogram, Meter, Second, SI},
};

const METER: Meter<f64> = Meter {
    value_unsafe: 1.0f64,
    _marker: PhantomData,
};
const KILOGRAM: Kilogram<f64> = Kilogram {
    value_unsafe: 1.0f64,
    _marker: PhantomData,
};
const SECOND: Second<f64> = Second {
    value_unsafe: 1.0f64,
    _marker: PhantomData,
};

derived!(
    si,
    SI: Meter2KilogramPerSecond = Meter * Meter * Kilogram / Second
);

const PLANCK: Meter2KilogramPerSecond<f64> = Meter2KilogramPerSecond {
    value_unsafe: 6.62607015e-34f64,
    _marker: PhantomData,
};

fn main() {
    let x = 3.0 * PLANCK;

    println!("{x}");
}
```

As I write this example, I see that there are a lot of things that can be improved, such as the use of const functions, and (relatively) new macro syntax.

**Comment by paholg** [comment]
That said, I'm surprised you would need 256 bits. Numbers smaller than planck's constant in SI units are expressible in 64 bits, and 128 bits can get you all the way down to 10^−4966.

Heck, if you used a 128 bit integer, expressing a planck length as 1, you could get all the way up to 2749 meters.

**Comment by MarkSwanson** [comment]
f64 only has precision down to about 15-16 digits, and I need around 42.
https://blog.demofox.org/2017/11/21/floating-point-precision/
(section: How Many Digits Can I Rely On?)

Ty for example. trying it out...

**Comment by paholg** [comment]
This is a limitation due to the orphan rules. It should work if you put the dimensioned quantity on the left-hand side.

**Comment by MarkSwanson** [comment]
Perhaps closer :-)
let x = PLANCK * qd!(3.0);
 expected struct `SI`, found struct `Quad`

**Comment by MarkSwanson** [comment]
This works :-)
let x = PLANCK.value_unsafe * y;

**Comment by paholg** [comment]
Yeah, that works, but you lose all of your units.

**Comment by MarkSwanson** [comment]
Because of orphan rules does it seem like the best way is to support qd / Quad inside of dimensioned?

**Comment by paholg** [comment]
Ah, now I remember (sorry, it's been a while since I've worked on this crate).

There's a fix for this in dimensioned using the `oibit` feature, but that requires nightly, and is currently broken (I'll work on getting a version of it working again here).

You should be able to do:

```
let x = si::Dimensionless::new(qd!(3.0)) * PLANCK;
```

**Comment by MarkSwanson** [comment]
I'm happy to use nightly.

**Comment by MarkSwanson** [comment]
Great! Will try it out shortly.

**Comment by MarkSwanson** [comment]
I'm thrilled to have this working! Thanks for your effort!
The output of the units is really nice: 
dimensioned: 0.000000000000000000000000000000001987821045 m^2*kg*s^-1
Will play around with superscript etc like this: m²×kg×s⁻¹

**Comment by MarkSwanson** [comment]
All of my brief testing today works fine.
Closing. Thanks again.
