### ISSUE TITLE
fmt String as Joules instead of MKS

### ISSUE THREAD

**Issue by MarkSwanson** [paholg/dimensioned#81]
I have a function like: fn() -> Joules.
However, when I print the Joules value I get something like: 5 m^2*kg*s^-2
Is there an easy way to print '5 Joules' instead?

If not, what do you think a good solution to this would be? (I'm not seeing an easy way to get access to the units to compare the set of units against 'Joule' etc.)
I'd be happy to take a crack at it.
Thanks!

**Comment by paholg** [comment]
You can get the underlying value by accessing the `value_unsafe` field, and enforce it's an energy with a type bound as so:

```rust
fn print_joule<T: Display>(energy: Joule<T>) {
    println!("{} J", energy.value_unsafe)
}
```

Alternatively, you could divide by 1 Joule:

```rust
let x = Joule::new(10.0);
println!("{} J", x / Joule::new(1.0));
```

**Comment by MarkSwanson** [comment]
Got it. I like the second one as if I see anything other than Joules I know I've messed up my units.
Thanks!
